on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy on Kapstan
        id: Kapstan
        uses: kapstan-io/deployment-action@rahul-added-commit-details-github-action-dev
        with:
          application_name: rahul-task2
          image_tag: backend
          kapstan_api_key: ${{ secrets.KAPSTAN_API }}
          wait_for_deployment: true
          commit_details: https://github.com/kapstan-io/shadowfax/commits/d0cb228ba5465db48b431f88c47547c72a125029

  
