name: Deploy on Kapstan

on: 
  push:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
         
      - name: Deploy on Kapstan
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7-dev 
        with:  
          application_name: github-test-4   
          image_tag: backend
          kapstan_api_key: ${{ secrets.KAPSTAN_API_3 }}
          wait_for_deployment: true 
