on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: kapstan-io/deployment-action@v0.7
        
      - name: Deploy on Kapstan
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7-dev
        with:
          application_name: rahul-github-task1
          image_tag: backend
          kapstan_api_key: ${{ secrets.KAPSTAN_API }}
          wait_for_deployment: true
          commit_details: https://github.com/kapstan-io/shadowfax/commit/123456789
      

  
