on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy on Kapstan
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7
        with:
          application_name: rahul-action
          image_tag: latest
          kapstan_api_key: ${{ secrets.KAPSTAN_API }}
          wait_for_deployment: true

