on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy on Kapstan
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7-dev
        with:
          application_name: rahul-github-2
          image_tag: backend 
          kapstan_api_key: ${{ secrets.KAPSTAN_API_3 }}
          wait_for_deployment: true
          commit_details: https://github.com/rahul-kapstan/task-1/commit/3222a8c237bfef62420b651edf392c2e90e157ca
